spring:
  application:
    name: limit-service
  config:
    import: optional:configserver:http://localhost:3546
    
  profiles:
    active:  test
   
   
server:
  port: 3596
  
#limit-service.minimum: 2
#limit-service.maximum: 1000
    
    
