server:
  port: 6060
spring:
 application:
    name: API-GATEWAY
 cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
          - Path= /userService/**
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
          - Path= /hotels/**
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
          - Path= /rating/**
        
#okta configuration for api gateway        
okta:
  oauth2:
    issuer: https://dev-56239259.okta.com/oauth2/default
    audience: api://default
    client-id: api://default
    client-secret: PGrwrBzC6nlrdgUGUVE6skkUNHLMIP8IdfLiXpRk
    scopes: openid, profile, email,  offline_access
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka
    fetch-registry: true
    register-with-eureka: true 
