server:
  port:  4234
spring:
  application:
    name: currency-exchange
    
  config:
    import: optional:configserver:http//localhost:3546
 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/Currency
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:4335/eureka
    register-with-eureka: true
  instance:
    hostname: localhost