Server:
  port: 8083
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8085
  
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
      web:
        exposure:
          include: health          

  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker: 
        register-health-indicator: true
        event-consumer-buffer-size:  10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled:  true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based
  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 3s
  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 4
        timeout-duration: 2s
  
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8763/eureka
#    fetch-registry: true
#    register-with-eureka: true
#    
#  instance:
#    prefer-ip-address: true
#  profiles:
#    active: dev
    
   
  
