server:
  port: 6535
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: RATING-SERVICE
  config:
    import: optional:configserver:http://localhost:8085
      
    
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8763/eureka
#    fetch-registry: true
#    register-with-eureka: true